project:
  type: website
  output-dir: docs
website:
  title: Corey Voller
  repo-url: https://cgvoller.github.io/
  search:
    location: navbar
    type: textbox
  navbar:
    right:
    - text: "?cvoller::about"
      href: about.qmd
    - text: "Posts()"
      href: posts.qmd
    - text: "miscellaneous()"
      file: misc.qmd
    - text: "CV()"
      file: CV.pdf
    - text: "Gallery()"
      file: gallery.qmd
    - icon: github
      href: https://github.com/cgvoller/
    - icon: linkedin
      href: https://www.linkedin.com/in/corey-v-027bb0198
format:
  html:
    mermaid:
      theme: dark
    #code-block-bg: true
    #code-block-border-left: "#000000"
    #code-block-border-left: true
    highlight-style: nord
    theme: slate
    css:
    - styles.css
    - include/webex.css
    smooth-scroll: true
    include-after-body: include/webex.js
editor: visual



